# Generated by Django 6.1 on 2026-09-16 03:33

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_categoria_compromissofinanceiro_movimentacao'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(models.F('usuario'), django.db.models.functions.text.Lower('nome'), models.F('tipo'), name='categoria_usuario_nome_tipo_unico'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(models.F('usuario'), django.db.models.functions.text.Lower('nome'), name='conta_usuario_nome_unico'),
        ),
    ]
