# Generated by Django 6.1 on 2026-09-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_categoria_categoria_usuario_nome_tipo_unico_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='compromissofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gt', 0)), name='compromisso_valor_total_positivo'),
        ),
        migrations.AddConstraint(
            model_name='compromissofinanceiro',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pago_recebido__gte', 0)), name='compromisso_valor_pago_recebido_nao_negativo'),
        ),
    ]
