# Generated by Django 6.1 on 2026-09-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_compromissofinanceiro_compromisso_valor_total_positivo_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='movimentacao_valor_positivo'),
        ),
    ]
